### ISSUE TITLE
Server OS error 2 (No such file or directory)

### ISSUE THREAD

**Issue by alicekanng** [M0dEx/quincy#96]
Hi! I'm trying to run the server binary on a docker container with the following configurations:

- Kernel: Linux 5.19.0-43-generic
- Architecture: x86-64
- OS: Ubuntu 24.04.1 LTS
- cargo 1.82.0
- rustc 1.82.0

I have the client running just fine on the exact same configurations, but on the server side I get this error.
<img width="980" alt="image" src="https://github.com/user-attachments/assets/2e1a32a6-9092-40cf-8fda-da06de2e3da2">

I've checked that all the required files (the server binary, Cargo.toml, examples/server.toml) all exist on the container, and have tried editing the script to use absolute paths, but unfortunately error persists.
Could I get some support on this error? Thanks a lot!

**Comment by M0dEx** [comment]
Hi!

Just to be sure, do the server certificate and its key exist and are at the location the `examples/server.toml` configuration file points to?

I probably should make these errors a bit more descriptive, since the current message is really vague.

**Comment by alicekanng** [comment]
Yep, sorry I forgot to add that part. The cert and key files are also located in the correct folder - and modifying the `server.toml` to point to their absolute paths did not solve the error.

**Comment by M0dEx** [comment]
Is the `users` file present in the `examples` folder as well?

**Comment by M0dEx** [comment]
Could you please try this again with version `0.11.2`? It should have more comprehensive error messages.

**Comment by alicekanng** [comment]
Unfortunately the same error. Are you able to replicate my configurations on a docker container yourself? I wonder if it's more helpful if you were to see it first hand.

**Comment by M0dEx** [comment]
I just noticed you're using Docker - in such case, you need to use the `host` network type and run Quincy under the root used, otherwise it will not have enough permission to run correctly.

**Comment by alicekanng** [comment]
I tried it out, but unfortunately it didn't fix the issue for me. I've also manually set the permissions to all required files to 777. Here's the container configuration if it provides some context: [server_container.txt](https://github.com/user-attachments/files/17628209/server_container.txt)

Is there anything in my machine configuration that you think could be causing this? We were able to run the server on a different machine (on the host, not a container this time) with a Linux 6.2.0-39-generic kernel and Ubuntu 22.04.5 LTS OS.

**Comment by M0dEx** [comment]
Hi, sorry for the delay.

This might be Quincy not playing well with Docker due to the TUN interfaces, as that is one of the deployment environments I did not really test.

I would like to support it, though, as it can be a very convenient way to get it up and running and it seems both OpenVPN and WireGuard support it without much fuss.

**Comment by M0dEx** [comment]
Tracking in #100.

**Comment by M0dEx** [comment]
@alicekanng what happens if you add the `NET_ADMIN` capability to the container, so something like `--cap=NET_ADMIN` in the `docker run` command?

**Comment by M0dEx** [comment]
I attempted to reproduce this locally - as long as the host OS and image OS match (eg. Linux-based distro on host/in image, MacOS on host/in image), adding the `--privileged` flag allows me to run Quincy in Docker.

**Comment by M0dEx** [comment]
Sure, it's in this branch: https://github.com/M0dEx/quincy/tree/%23100/docker-image

**Comment by M0dEx** [comment]
Could you try it with `m0dex/quincy:latest`?

**Comment by M0dEx** [comment]
Hi @alicekanng!

Any updates on your issue? I have released `0.12.2` with correctly set-up capabilities, so everything other than DNS, which I have found night-impossible to support in Docker, should be working.

**Comment by alicekanng** [comment]
Hey! Sorry about the delay. I switched gears to running the client and server on VMs, and it worked like magic on the first go! That said, I'm happy to help troubleshoot this issue - as it seems like my machine is particularly finicky about Docker.

Just to confirm, do I need to change any of the repo names or config files (other than generating the certificates) when running it from the docker image? I now get an error saying "failed to load configuration file /etc/quincy/server.toml".

**Comment by M0dEx** [comment]
You shouldn't need to, but the Docker image uses a non-root user, so you should make sure the configuration directory and files are readable by the user.

**Comment by M0dEx** [comment]
> Sorry, then wouldn't I need to change the directory containing the config files from examples to etc/quincy?

Not necessarily; you need to mount the directory into `/etc/quincy` in the Docker container (see the README), but you have to either `chown` or `chmod` the directory and files so that they are readable by the user in the Docker container.

**Comment by alicekanng** [comment]
Ah I see. I tried setting the directory and individual config files to 777, but I'm still getting this error.
<img width="1446" alt="image" src="https://github.com/user-attachments/assets/1a0cd57a-f7df-4907-9009-c3c8ad2f2ea9">

**Comment by M0dEx** [comment]
Are you by any chance using SELinux?

**Comment by alicekanng** [comment]
I'm not.

**Comment by M0dEx** [comment]
What happens if you run the Docker container with all the same parameters, but instead of calling `quincy-server`, you call `cat /etc/quincy/server.toml`?

**Comment by alicekanng** [comment]
I'm getting `cat: can't open '/etc/quincy/server.toml': No such file or directory`. Do you think this is related to the original error message I encountered?

**Comment by M0dEx** [comment]
It sounds as if Docker was not mounting the volume properly.

What does `docker run ... ls -la /etc/quincy` show?

**Comment by alicekanng** [comment]
I don't see any files in `/etc/quincy`.
<img width="423" alt="image" src="https://github.com/user-attachments/assets/8dd22dfe-a160-452c-a230-f3d9bac5a18f">

**Comment by M0dEx** [comment]
It seems like the volume does not get mounted correctly, possibly due to permission issues.

Where is the directory you are mounting located at?

**Comment by M0dEx** [comment]
Closing as stale.
